"""Asterisk helpers shared by Ameyo and FreePBX."""

from __future__ import annotations

from sipauto.models import Inventory, SipDriver


def render_rtp_conf_snippet(inv: Inventory) -> str:
    return (
        "; Generated by SIPAUTO — ensure RTP range matches firewall both sides\n"
        f"rtpstart={inv.network.rtp_start}\n"
        f"rtpend={inv.network.rtp_end}\n"
    )


def reload_commands(inv: Inventory) -> list[str]:
    cmds = [
        "asterisk -rx 'rtp reload' || true",
    ]
    if inv.sip_driver == SipDriver.PJSIP or inv.platform.value == "freepbx":
        cmds.append("asterisk -rx 'module reload res_pjsip.so' || asterisk -rx 'pjsip reload' || true")
        cmds.append("asterisk -rx 'pjsip show registrations' || true")
        cmds.append("asterisk -rx 'pjsip show endpoints' || true")
    if inv.sip_driver == SipDriver.CHAN_SIP or inv.platform.value == "ameyo_asterisk":
        cmds.append("asterisk -rx 'sip reload' || true")
        cmds.append("asterisk -rx 'sip show registry' || true")
        cmds.append("asterisk -rx 'sip show peers' || true")
    return cmds


def registry_check_command(inv: Inventory) -> str:
    if inv.sip_driver == SipDriver.PJSIP:
        return "asterisk -rx 'pjsip show registrations'"
    return "asterisk -rx 'sip show registry'"


def network_reload_commands(iface: str) -> list[str]:
    return [
        f"nmcli connection reload || true",
        f"ifdown {iface} 2>/dev/null || true",
        f"ifup {iface} 2>/dev/null || nmcli device reapply {iface} 2>/dev/null || true",
        f"ip route show | grep -E '{iface}|via' || true",
        f"ip addr show {iface} || true",
    ]
